# Generated by Django 4.1.5 on 2023-01-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student name')),
                ('std', models.IntegerField(verbose_name='Class')),
                ('division', models.CharField(max_length=3, verbose_name='Division')),
                ('dob', models.DateField(verbose_name='DOB')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
            ],
        ),
    ]
